name: Bootstrap Terraform Backend

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name StorageRG \
            --location italynorth

      - name: Create Storage Account
        run: |
          az storage account create \
            --name taskboardsadavidnakov \
            --resource-group StorageRG \
            --location italynorth \
            --sku Standard_LRS \
            --kind StorageV2

      - name: Create Blob Container
        run: |
          az storage container create \
            --name taskboardstoragedavid \
            --account-name taskboardsadavidnakov

      - name: Save backend config
        run: |
          echo "TF_BACKEND_RG=StorageRG" >> backend.txt
          echo "TF_BACKEND_SA=taskboardsadavidnakov" >> backend.txt
          echo "TF_BACKEND_CONTAINER=taskboardstoragedavid" >> backend.txt

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-config
          path: backend.txt


